version: '3.8'

services:
  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306" # MySQL port
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80" # Access phpMyAdmin on port 8080
    depends_on:
      - mysql
    networks:
      - mysql_network

# Named volumes for MySQL data persistence
volumes:
  mysql_data:

    # Network for inter-container communication
networks:
  mysql_network:
